[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-10_x", "openssl"]

[phases.install]
cmds = ["npm install -g corepack@0.24.1 && corepack enable pnpm", "pnpm i --frozen-lockfile"]

[phases.build]
cmds = ["pnpm install && pnpm build"]

[start]
cmd = "pnpm start"
